apiVersion: skaffold/v4beta9
kind: Config
build:
  # tagPolicy: 
  #   sha256: {}
  artifacts:
    - image: zoodruimage
      context: .
      docker:
        dockerfile: docker/dru/Dockerfile

deploy:
  helm:
    releases:
      - name: eoap-zoo-project-localstack
        remoteChart: localstack/localstack
        namespace: eoap-zoo-project
        createNamespace: true
        setValues:
          service.type: ClusterIP
          enableStartupScripts: true
          startupScriptContent: |
            #!/bin/bash

            awslocal s3 mb s3://results

      - name: zoo-project-dru
        remoteChart: zoo-project/zoo-project-dru
        namespace: eoap-zoo-project
        createNamespace: true
        version: 0.4.14
        valuesFiles:
        - values.yaml
        setValueTemplates:
          iam.enabled: false
          # EOEPCA cookiecutter
          #cookiecutter.templateUrl: https://github.com/EOEPCA/eoepca-proc-service-template.git
          #cookiecutter.templateBranch: feature/python3.8
          # Standard cookiecutter
          cookiecutter.templateUrl: https://github.com/eoap/zoo-service-template.git
          cookiecutter.templateBranch: feature-secrets-nodeselector-imagepullsecrets
          filter_in.enabled: true
          filter_out.enabled: true
          zoofpm.image.repository: "{{.IMAGE_REPO_zoodruimage}}"
          zoofpm.image.tag: "{{.IMAGE_TAG_zoodruimage}}"
          zoofpm.image.pullPolicy: IfNotPresent
          zookernel.image.repository: "{{.IMAGE_REPO_zoodruimage}}"
          zookernel.image.tag: "{{.IMAGE_TAG_zoodruimage}}" 
          zookernel.image.pullPolicy: IfNotPresent

          # Persistence settings (should be same in the original chart)
          persistence.procServicesAccessMode: ReadWriteMany

          # RabbitMQ resource limits
          rabbitmq.resource.limits.memory: 2048Mi

          workflow.additionalInputs:
            s3_bucket: results
            region_name: us-east-1
            aws_secret_access_key: test
            aws_access_key_id: test
            endpoint_url: http://eoap-zoo-project-localstack.eoap-zoo-project.svc.cluster.local:4566

profiles:

  - name: hostpath
    patches:
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/workflow.storageClass
        value: hostpath
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/persistence.storageClass
        value: hostpath
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/persistence.procServicesStorageClass
        value: hostpath
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/persistence.tmpStorageClass
        value: hostpath

  - name: wes
    patches:
      - op: replace
        path: /deploy/helm/releases/1/setValueTemplates/cookiecutter.templateUrl
        value: https://github.com/gfenoy/eoepca-proc-service-template-wes.git
      - op: replace
        path: /deploy/helm/releases/1/setValueTemplates/cookiecutter.templateBranch
        value: develop
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/workflow.inputs.WES_URL
        value: "http://192.168.1.59:8100/ga4gh/wes/v1/"
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/workflow.inputs.WES_USER
        value: "test"
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/workflow.inputs.WES_PASSWORD
        value: "$$2y$$12$$ci.4U63YX83CwkyUrjqxAucnmi2xXOIlEF6T/KdP9824f1Rf1iyNG"

  - name: argo
    patches:
      - op: replace
        path: /deploy/helm/releases/1/setValueTemplates/workflow.additionalInputs.s3_bucket
        value: results
      - op: replace
        path: /deploy/helm/releases/1/setValueTemplates/workflow.additionalInputs.region_name
        value: us-east-1
      - op: replace
        path: /deploy/helm/releases/1/setValueTemplates/workflow.additionalInputs.aws_secret_access_key
        value: minio-admin
      - op: replace
        path: /deploy/helm/releases/1/setValueTemplates/workflow.additionalInputs.aws_access_key_id
        value: minio-admin
      - op: replace
        path: /deploy/helm/releases/1/setValueTemplates/workflow.additionalInputs.endpoint_url
        value: http://minio.ns1.svc.cluster.local:9000
      - op: replace
        path: /deploy/helm/releases/1/setValueTemplates/cookiecutter.templateUrl
        value: https://github.com/gfenoy/zoo-argo-wf-proc-service-template.git
      - op: replace
        path: /deploy/helm/releases/1/setValueTemplates/cookiecutter.templateBranch
        value: develop
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/workflow.argo.enabled
        value: true
      - op: add
        path: /deploy/helm/releases/1/setValueTemplates/workflow.argo.wfToken
        value: "<ARGO_WF_TOKEN>"

portForward:
  - resourceType: service
    resourceName: zoo-project-dru-service
    namespace: eoap-zoo-project
    address: localhost
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: eoap-zoo-project-localstack
    namespace: eoap-zoo-project
    address: localhost
    port: 4566
    localPort: 8022
