TROOT= $(ZOOK_DIR)
!INCLUDE $(ZOOK_DIR)/nmake.opt

FILES=$(ZOOK_DIR)/libzoo_service.lib

cgi-env/ogr_service.zo: service.c
	$(CPP)  /D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -DZOO_SERVICE -I$(GDAL_DIR)/frmts/ $(CFLAGS) /c service.c
	link /dll /out:cgi-env/ogr_service.zo  ./service.obj $(FILES) $(LDFLAGS) $(GEOS_DIR)/lib/geos_c.lib /FORCE:MULTIPLE

clean:
	erase cgi-env\ogr_service.*

