TROOT= $(ZOOK_DIR)
!INCLUDE $(ZOOK_DIR)/nmake.opt

FILES=$(ZOOK_DIR)/libzoo_service.lib

CFLAGS=-I$(GEODIR)/include -I$(TOOLS)/include -I../../../zoo-kernel/ -I./ -DGDAL_1_5_0 -DZOO_SERVICE -DLINUX_FREE_ISSUE -DDEBUG
CPP=cl /TP 

cgi-env/ogr2ogr_service.zo: service.c
	$(CPP) $(CFLAGS) /c service.c
	link /dll /out:cgi-env/ogr2ogr_service.zo ./service.obj  $(FILES) $(LDFLAGS)

clean:
	rm -f cgi-env/ogr2ogr_service.zso
