#get the latest python base image from the docker hub
FROM python:latest

#set the working directory
WORKDIR usr/app/zooqgis

#copy the python files to the working directory
copy helloWorld.py ./

#run the python file
CMD ["python","helloWorld.py"]