services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    command:
      - start-dev
      - --http-enabled=true
      - --verbose
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8099:8080"
    networks:
      front-tier:
        ipv4_address: 172.37.0.18

networks:
  front-tier:
    ipam:
      driver: default
      config:
        - subnet: "172.37.0.0/24"