name: Documentation building and deployment 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  documentation-build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Documentation using sphinx Docker image
      run: |
        docker run --rm -v $(pwd)/docs:/docs sphinxdoc/sphinx:6.2.0 make html ;
        ls -ailtr docs/_build/ docs/_build/html ;
        sudo chown runner:docker -R docs/_build/
        touch docs/_build/html/.nojekyll ;
        cp docs/_config.yml docs/_build/html/
    - name: Build the Documentation using doxygen Docker image
      run: |
        docker run --rm -v $(pwd)/zoo-project/zoo-kernel:/data hrektts/doxygen doxygen  ;
        cp -r zoo-project/zoo-kernel/html docs/_build/html/C_API
    - name: Build documentation using JSDoc
      run: |
        npm install -g jsdoc ;
        npm install -g ink-docstrap ;
        npm install -g taffydb ;
        cd zoo-project/zoo-client/lib/js/wps-client ;
        jsdoc *js -R ../../../../../README.md -t /usr/local/lib/node_modules/ink-docstrap/template  ;
        cd ../../../../.. ;
        cp -r zoo-project/zoo-client/lib/js/wps-client/out docs/_build/html/JS_API
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        repository-name: ZOO-Project/docs
        branch: gh-pages
        folder: docs/_build/html
        ssh-key: ${{ secrets.DEPLOY_KEY }}
