name: Check Vulnerabilities

on:
  push:
    branches:
      - main
      - vulnerabilities-check
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
      - vulnerabilities-check
    paths-ignore:
      - '**.md'

  release:
    types:
      - released

jobs:
  vulnerabilities:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy filesystem scan
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: fs
          scan-ref: .
          scanners: vuln,misconfig,secret
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build \
            -t zoo-project-dru:${{ github.sha }} \
            -f docker/dru/Dockerfile .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.35.0
        with:
          scan-type: image
          image-ref: zoo-project-dru:${{ github.sha }}
          vuln-type: os,library
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 0
